FROM ubuntu:16.04

RUN apt-get update && apt-get install -y \
    wget \
    tar \
    bzip2 \
    python3 \ 
    # Add more dependencies if needed \
    && rm -rf /var/lib/apt/lists/*


WORKDIR /home

COPY setup.sh setup.sh

RUN chmod +x setup.sh

RUN ./setup.sh

CMD ["/bin/sh"]